[package]
name = "char"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color_eyre = { workspace = true }

[workspace]
members = ["crates/char_core"]

[workspace.dependencies]
color_eyre = "*"
