[workspace]
members = [
  "examples/service/char_plan",
  "crates/char_cli",
  "crates/char_sdk",
  "crates/char_sdk_derive",
]

[workspace.dependencies]
eyre = "0.6.8"
color-eyre = "0.6.2"
tokio = { version = "1.25.0", features = ["full"] }
tracing = { version = "0.1.37", features = ["log"] }
